name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn motor[asyncio] pydantic beanie

    - name: Run Tests (Optional)
      run: |
        # Add any test commands if applicable

    - name: Deploy (Optional)
      run: |
        # Add deployment commands if applicable

